# Dependencies
gems:             [jekyll-paginate, redcarpet, jekyll-gist, rouge]
markdown:         redcarpet

redcarpet:
  extensions: ["tables", "fenced_code_blocks", "footnotes"]

# Permalinks
permalink:        pretty

# Setup
title:            Joey Lange
tagline:          'Bit Shepherd'
description:      ''
url:              'http://josefdlange.com'
baseurl:          ''

exclude: ["README.md", "Gemfile", "Gemfile.lock", ".gitignore", "LICENSE.md"]

author:
  name:           'Joey Lange'
  url:            https://twitter.com/josefdlange

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/josefdlange/josefdlange.github.com
