# Dependencies
gems:             [jekyll-paginate, redcarpet, jekyll-gist, rouge]
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Josef Lange
tagline:          'Huge Nerd'
description:      ''
url:              http://josefdlange.com
baseurl:          http://josefdlange.com

author:
  name:           'Josef Lange'
  url:            https://twitter.com/josefdlange

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/josefdlange/josefdlange.github.com
